Models:
- Config: configs/runes/rtmpose/rtmpose-m_8xb32-60e_coco-rune-256x256.py
  In Collection: RTMPose
  Metadata:
    Architecture:
    - RTMPose
    Training Data: COCO-Rune
  Name: rtmpose-m_8xb32-60e_coco-rune-256x256
  Results:
  - Dataset: COCO-Rune
    Metrics:
      NME: 0.0466
    Task: Rune 2D Keypoint
  #Weights: https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmpose-m_simcc-coco-wholebody-face_pt-aic-coco_60e-256x256-62026ef2_20230228.pth
